INSERT INTO HOSPITAL(NAME, STREET_NAME, STREET_NUMBER, CITY, AREA_CODE, PHONE_NUMBER)
VALUES('Hospital Italiano Garibaldi', 'Virasoro', 1249, 'Rosario', '0341', '0810-555-0505');
INSERT INTO HOSPITAL(NAME, STREET_NAME, STREET_NUMBER, CITY, AREA_CODE, PHONE_NUMBER)
VALUES('Hospital Español', 'Sarmiento', 3150, 'Rosario', '0341', '485-8700');
INSERT INTO DEPARTMENT(ID, DEPT_NAME, HOSPITAL)
VALUES(1, 'CARDIOLOGIA', 'Hospital Italiano Garibaldi');
INSERT INTO DEPARTMENT(ID, DEPT_NAME, HOSPITAL)
VALUES(2, 'NEONATOLOGIA', 'Hospital Italiano Garibaldi');
INSERT INTO DEPARTMENT(ID, DEPT_NAME, HOSPITAL)
VALUES(3, 'GUARDIA', 'Hospital Italiano Garibaldi');
INSERT INTO DEPARTMENT(ID, DEPT_NAME, HOSPITAL)
VALUES(4, 'HEMOTERAPIA', 'Hospital Italiano Garibaldi');